set_property PACKAGE_PIN AF5 [get_ports {gt_clk_clk_n[0]}]
set_property PACKAGE_PIN AF6 [get_ports {gt_clk_clk_p[0]}]
create_clock -period 6.734 -name clk_ethernet [get_ports gt_clk_clk_p]
set_property IOSTANDARD LVCMOS18 [get_ports {geg_det_n[0]}]
set_property PACKAGE_PIN K15 [get_ports {geg_det_n[0]}]
set_property PULLUP true [get_ports {geg_det_n[0]}]
set_property PACKAGE_PIN AP11 [get_ports fan_on]
set_property IOSTANDARD LVCMOS33 [get_ports fan_on]
set_property PACKAGE_PIN AJ18 [get_ports sys_clk_clk_p]
set_property PACKAGE_PIN AK18 [get_ports sys_clk_clk_n]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports sys_clk_clk_p]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports sys_clk_clk_n]
set_property PACKAGE_PIN AD34 [get_ports {ims_pwr_oe[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ims_pwr_oe[0]}]
set_property PACKAGE_PIN AA29 [get_ports {sys_rst[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sys_rst[0]}]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT2]] -group [get_clocks -of_objects [get_pins {design_1_i/aurora_8b10b_interfp_0/inst/gt_wrapper_i/aurora_8b10b_gth_i/inst/gen_gtwizard_gthe4_top.aurora_8b10b_gth_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[1].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
