## clk
set_property PACKAGE_PIN AJ18 [get_ports C0_SYS_CLK_0_clk_p]
set_property PACKAGE_PIN AK18 [get_ports C0_SYS_CLK_0_clk_n]

#Light
set_property PACKAGE_PIN AE13 [get_ports LEDEn]
set_property PACKAGE_PIN AH11 [get_ports MLLEn]
set_property PACKAGE_PIN AF12 [get_ports SLLEn]
set_property IOSTANDARD LVCMOS33 [get_ports LEDEn]
set_property IOSTANDARD LVCMOS33 [get_ports MLLEn]
set_property IOSTANDARD LVCMOS33 [get_ports SLLEn]

## image sensor
set_property PACKAGE_PIN V5 [get_ports img_clk_n]
set_property PACKAGE_PIN V6 [get_ports img_clk_p]

set_property PACKAGE_PIN W31 [get_ports SCLK]
set_property PACKAGE_PIN V31 [get_ports MCLK]
set_property PACKAGE_PIN V34 [get_ports XCE]
set_property PACKAGE_PIN U34 [get_ports X_MOSI]
set_property PACKAGE_PIN Y32 [get_ports Xmaster]
set_property PACKAGE_PIN Y31 [get_ports XHS]
set_property PACKAGE_PIN W34 [get_ports XVS]
set_property PACKAGE_PIN V33 [get_ports Xtrigger1]
set_property PACKAGE_PIN Y30 [get_ports Xtrigger2]
set_property PACKAGE_PIN W30 [get_ports X_MISO]
set_property PACKAGE_PIN Y33 [get_ports XCLR]
set_property PACKAGE_PIN W33 [get_ports omode]
set_property PACKAGE_PIN AD33 [get_ports {slavemode[0]}]
set_property PACKAGE_PIN AA33 [get_ports {slavemode[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports XCLR]
set_property IOSTANDARD LVCMOS18 [get_ports omode]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports X_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports X_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports XCE]
set_property IOSTANDARD LVCMOS18 [get_ports Xtrigger1]
set_property IOSTANDARD LVCMOS18 [get_ports Xtrigger2]
set_property IOSTANDARD LVCMOS18 [get_ports {slavemode[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {slavemode[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports Xmaster]
set_property IOSTANDARD LVCMOS18 [get_ports XHS]
set_property IOSTANDARD LVCMOS18 [get_ports XVS]